echo “source .zshrc”

# prezto.
if [[ -s "${HOME}/.zprezto/init.zsh" ]]; then
  source "${HOME}/.zprezto/init.zsh"
fi

ZSH_DIR=${HOME}/dotfiles/src/zsh

# alias.
if [[ -f "${ZSH_DIR}/zshrc.alias" ]]; then
  source "${ZSH_DIR}/zshrc.alias"
fi

# osx.
if [[ -f "${ZSH_DIR}/zshrc.osx" ]]; then
  source "${ZSH_DIR}/zshrc.osx"
fi
